# Debian with OpenJDK 7

FROM debian:jessie

MAINTAINER Andre Nascimento <andreluiznsilva@gmail.com>

RUN apt-get update
RUN apt-get -y install wget

RUN apt-get -y install openjdk-7-jre-headless

CMD java -version