# Sonar 5.1 image

FROM sonarqube:5.1

MAINTAINER Andre Nascimento <andreluiznsilva@gmail.com>

ENV SONARQUBE_JDBC_USERNAME sonar
ENV SONARQUBE_JDBC_PASSWORD sonar*123
ENV SONARQUBE_JDBC_URL jdbc:h2:tcp://localhost:9092/sonar