# Oracle Image

FROM wnameless/oracle-xe-11g

MAINTAINER Andre Nascimento <andreluiznsilva@gmail.com>

ADD XE.sql /u01/app/oracle/product/11.2.0/xe/config/scripts/XE.sql
ADD init.sql /u01/app/oracle/product/11.2.0/xe/config/scripts/init.sql