# MySql image

FROM mysql:5.7

MAINTAINER Andre Nascimento <andreluiznsilva@gmail.com>

ENV DB default
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABASE ${DB}
ENV MYSQL_USER ${DB}
ENV MYSQL_PASSWORD ${DB}

EXPOSE 3306